apiVersion: v1
kind: Service
metadata:
  name: ai-advisor
  labels:
    app: ai-advisor
spec:
  type: LoadBalancer
  selector:
    app: ai-advisor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
